# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Dirk/Grad_School/525.742.8VL_SOC/HW/Module3/lab3b/vivado/lab3b.srcs/sources_1/bd/proc_system/ip/proc_system_reset_and_leds_0/proc_system_reset_and_leds_0.xci
# IP: The module: 'proc_system_reset_and_leds_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Dirk/Grad_School/525.742.8VL_SOC/HW/Module3/lab3b/vivado/lab3b.gen/sources_1/bd/proc_system/ip/proc_system_reset_and_leds_0/proc_system_reset_and_leds_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'proc_system_reset_and_leds_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Dirk/Grad_School/525.742.8VL_SOC/HW/Module3/lab3b/vivado/lab3b.gen/sources_1/bd/proc_system/ip/proc_system_reset_and_leds_0/proc_system_reset_and_leds_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'proc_system_reset_and_leds_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Dirk/Grad_School/525.742.8VL_SOC/HW/Module3/lab3b/vivado/lab3b.gen/sources_1/bd/proc_system/ip/proc_system_reset_and_leds_0/proc_system_reset_and_leds_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'proc_system_reset_and_leds_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/Dirk/Grad_School/525.742.8VL_SOC/HW/Module3/lab3b/vivado/lab3b.srcs/sources_1/bd/proc_system/ip/proc_system_reset_and_leds_0/proc_system_reset_and_leds_0.xci
# IP: The module: 'proc_system_reset_and_leds_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Dirk/Grad_School/525.742.8VL_SOC/HW/Module3/lab3b/vivado/lab3b.gen/sources_1/bd/proc_system/ip/proc_system_reset_and_leds_0/proc_system_reset_and_leds_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'proc_system_reset_and_leds_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Dirk/Grad_School/525.742.8VL_SOC/HW/Module3/lab3b/vivado/lab3b.gen/sources_1/bd/proc_system/ip/proc_system_reset_and_leds_0/proc_system_reset_and_leds_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'proc_system_reset_and_leds_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Dirk/Grad_School/525.742.8VL_SOC/HW/Module3/lab3b/vivado/lab3b.gen/sources_1/bd/proc_system/ip/proc_system_reset_and_leds_0/proc_system_reset_and_leds_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'proc_system_reset_and_leds_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
