
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2022.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2023 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[XPAR_XGPIO_NUM_INSTANCES] =
{
	{
		XPAR_AXI_RESETN_DEVICE_ID,
		XPAR_AXI_RESETN_BASEADDR,
		XPAR_AXI_RESETN_INTERRUPT_PRESENT,
		XPAR_AXI_RESETN_IS_DUAL
	},
	{
		XPAR_AXI_PHASE_SIG_DEVICE_ID,
		XPAR_AXI_PHASE_SIG_BASEADDR,
		XPAR_AXI_PHASE_SIG_INTERRUPT_PRESENT,
		XPAR_AXI_PHASE_SIG_IS_DUAL
	},
	{
		XPAR_AXI_PHASE_TUNE_DEVICE_ID,
		XPAR_AXI_PHASE_TUNE_BASEADDR,
		XPAR_AXI_PHASE_TUNE_INTERRUPT_PRESENT,
		XPAR_AXI_PHASE_TUNE_IS_DUAL
	}
};


