# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Dirk/Grad_School/525.742.8VL_SOC/HW/Module1/lab1a/lab1a.srcs/sources_1/bd/proc_system/ip/proc_system_axi_gpio_0_0/proc_system_axi_gpio_0_0.xci
# IP: The module: 'proc_system_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Dirk/Grad_School/525.742.8VL_SOC/HW/Module1/lab1a/lab1a.gen/sources_1/bd/proc_system/ip/proc_system_axi_gpio_0_0/proc_system_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'proc_system_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Dirk/Grad_School/525.742.8VL_SOC/HW/Module1/lab1a/lab1a.gen/sources_1/bd/proc_system/ip/proc_system_axi_gpio_0_0/proc_system_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'proc_system_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Dirk/Grad_School/525.742.8VL_SOC/HW/Module1/lab1a/lab1a.gen/sources_1/bd/proc_system/ip/proc_system_axi_gpio_0_0/proc_system_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'proc_system_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/Dirk/Grad_School/525.742.8VL_SOC/HW/Module1/lab1a/lab1a.srcs/sources_1/bd/proc_system/ip/proc_system_axi_gpio_0_0/proc_system_axi_gpio_0_0.xci
# IP: The module: 'proc_system_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Dirk/Grad_School/525.742.8VL_SOC/HW/Module1/lab1a/lab1a.gen/sources_1/bd/proc_system/ip/proc_system_axi_gpio_0_0/proc_system_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'proc_system_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Dirk/Grad_School/525.742.8VL_SOC/HW/Module1/lab1a/lab1a.gen/sources_1/bd/proc_system/ip/proc_system_axi_gpio_0_0/proc_system_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'proc_system_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Dirk/Grad_School/525.742.8VL_SOC/HW/Module1/lab1a/lab1a.gen/sources_1/bd/proc_system/ip/proc_system_axi_gpio_0_0/proc_system_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'proc_system_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
