function Hd = filter1
%FILTER1 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.10 and Signal Processing Toolbox 8.6.
% Generated on: 07-Mar-2023 13:56:07

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 125000000;  % Sampling Frequency

Fpass = 576000;          % Passband Frequency
Fstop = 2549000;         % Stopband Frequency
Dpass = 0.028774368332;  % Passband Ripple
Dstop = 0.0001;          % Stopband Attenuation
dens  = 20;              % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fpass, Fstop]/(Fs/2), [1 0], [Dpass, Dstop]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
