# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Dirk/Grad_School/525.742.8VL_SOC/HW/Module4/Lab4/vivado/lab4.srcs/sources_1/bd/proc_system/ip/proc_system_system_ila_0_1/proc_system_system_ila_0_1.xci
# IP: The module: 'proc_system_system_ila_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/Dirk/Grad_School/525.742.8VL_SOC/HW/Module4/Lab4/vivado/lab4.gen/sources_1/bd/proc_system/ip/proc_system_system_ila_0_1/bd_0/bd_395b.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_395b || ORIG_REF_NAME==bd_395b} -quiet] -quiet

# IP: d:/Dirk/Grad_School/525.742.8VL_SOC/HW/Module4/Lab4/vivado/lab4.gen/sources_1/bd/proc_system/ip/proc_system_system_ila_0_1/bd_0/ip/ip_0/bd_395b_ila_lib_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_395b_ila_lib_0 || ORIG_REF_NAME==bd_395b_ila_lib_0} -quiet] -quiet

# IP: d:/Dirk/Grad_School/525.742.8VL_SOC/HW/Module4/Lab4/vivado/lab4.gen/sources_1/bd/proc_system/ip/proc_system_system_ila_0_1/bd_0/ip/ip_1/bd_395b_g_inst_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_395b_g_inst_0 || ORIG_REF_NAME==bd_395b_g_inst_0} -quiet] -quiet

# XDC: d:/Dirk/Grad_School/525.742.8VL_SOC/HW/Module4/Lab4/vivado/lab4.gen/sources_1/bd/proc_system/ip/proc_system_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_395b_ila_lib_0 || ORIG_REF_NAME==bd_395b_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Dirk/Grad_School/525.742.8VL_SOC/HW/Module4/Lab4/vivado/lab4.gen/sources_1/bd/proc_system/ip/proc_system_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_395b_ila_lib_0 || ORIG_REF_NAME==bd_395b_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Dirk/Grad_School/525.742.8VL_SOC/HW/Module4/Lab4/vivado/lab4.gen/sources_1/bd/proc_system/ip/proc_system_system_ila_0_1/bd_0/ip/ip_0/bd_395b_ila_lib_0_ooc.xdc

# XDC: d:/Dirk/Grad_School/525.742.8VL_SOC/HW/Module4/Lab4/vivado/lab4.gen/sources_1/bd/proc_system/ip/proc_system_system_ila_0_1/bd_0/bd_395b_ooc.xdc

# XDC: d:/Dirk/Grad_School/525.742.8VL_SOC/HW/Module4/Lab4/vivado/lab4.gen/sources_1/bd/proc_system/ip/proc_system_system_ila_0_1/proc_system_system_ila_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'proc_system_system_ila_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/Dirk/Grad_School/525.742.8VL_SOC/HW/Module4/Lab4/vivado/lab4.srcs/sources_1/bd/proc_system/ip/proc_system_system_ila_0_1/proc_system_system_ila_0_1.xci
# IP: The module: 'proc_system_system_ila_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/Dirk/Grad_School/525.742.8VL_SOC/HW/Module4/Lab4/vivado/lab4.gen/sources_1/bd/proc_system/ip/proc_system_system_ila_0_1/bd_0/bd_395b.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_395b || ORIG_REF_NAME==bd_395b} -quiet] -quiet

# IP: d:/Dirk/Grad_School/525.742.8VL_SOC/HW/Module4/Lab4/vivado/lab4.gen/sources_1/bd/proc_system/ip/proc_system_system_ila_0_1/bd_0/ip/ip_0/bd_395b_ila_lib_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_395b_ila_lib_0 || ORIG_REF_NAME==bd_395b_ila_lib_0} -quiet] -quiet

# IP: d:/Dirk/Grad_School/525.742.8VL_SOC/HW/Module4/Lab4/vivado/lab4.gen/sources_1/bd/proc_system/ip/proc_system_system_ila_0_1/bd_0/ip/ip_1/bd_395b_g_inst_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_395b_g_inst_0 || ORIG_REF_NAME==bd_395b_g_inst_0} -quiet] -quiet

# XDC: d:/Dirk/Grad_School/525.742.8VL_SOC/HW/Module4/Lab4/vivado/lab4.gen/sources_1/bd/proc_system/ip/proc_system_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_395b_ila_lib_0 || ORIG_REF_NAME==bd_395b_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Dirk/Grad_School/525.742.8VL_SOC/HW/Module4/Lab4/vivado/lab4.gen/sources_1/bd/proc_system/ip/proc_system_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_395b_ila_lib_0 || ORIG_REF_NAME==bd_395b_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Dirk/Grad_School/525.742.8VL_SOC/HW/Module4/Lab4/vivado/lab4.gen/sources_1/bd/proc_system/ip/proc_system_system_ila_0_1/bd_0/ip/ip_0/bd_395b_ila_lib_0_ooc.xdc

# XDC: d:/Dirk/Grad_School/525.742.8VL_SOC/HW/Module4/Lab4/vivado/lab4.gen/sources_1/bd/proc_system/ip/proc_system_system_ila_0_1/bd_0/bd_395b_ooc.xdc

# XDC: d:/Dirk/Grad_School/525.742.8VL_SOC/HW/Module4/Lab4/vivado/lab4.gen/sources_1/bd/proc_system/ip/proc_system_system_ila_0_1/proc_system_system_ila_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'proc_system_system_ila_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
