# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Dirk/Grad_School/525.742.8VL_SOC/HW/Module5/lab5/vivado/lab5.srcs/sources_1/bd/proc_system/ip/proc_system_fir_compiler_1_0/proc_system_fir_compiler_1_0.xci
# IP: The module: 'proc_system_fir_compiler_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Dirk/Grad_School/525.742.8VL_SOC/HW/Module5/lab5/vivado/lab5.gen/sources_1/bd/proc_system/ip/proc_system_fir_compiler_1_0/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'proc_system_fir_compiler_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Dirk/Grad_School/525.742.8VL_SOC/HW/Module5/lab5/vivado/lab5.gen/sources_1/bd/proc_system/ip/proc_system_fir_compiler_1_0/proc_system_fir_compiler_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'proc_system_fir_compiler_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/Dirk/Grad_School/525.742.8VL_SOC/HW/Module5/lab5/vivado/lab5.srcs/sources_1/bd/proc_system/ip/proc_system_fir_compiler_1_0/proc_system_fir_compiler_1_0.xci
# IP: The module: 'proc_system_fir_compiler_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Dirk/Grad_School/525.742.8VL_SOC/HW/Module5/lab5/vivado/lab5.gen/sources_1/bd/proc_system/ip/proc_system_fir_compiler_1_0/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'proc_system_fir_compiler_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Dirk/Grad_School/525.742.8VL_SOC/HW/Module5/lab5/vivado/lab5.gen/sources_1/bd/proc_system/ip/proc_system_fir_compiler_1_0/proc_system_fir_compiler_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'proc_system_fir_compiler_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
