# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Module1/Zybo-Z7-Master.xdc

# Block Designs: bd/proc_system/proc_system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==proc_system || ORIG_REF_NAME==proc_system} -quiet] -quiet

# IP: bd/proc_system/ip/proc_system_processing_system7_0_0/proc_system_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==proc_system_processing_system7_0_0 || ORIG_REF_NAME==proc_system_processing_system7_0_0} -quiet] -quiet

# IP: bd/proc_system/ip/proc_system_axi_gpio_0_0/proc_system_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==proc_system_axi_gpio_0_0 || ORIG_REF_NAME==proc_system_axi_gpio_0_0} -quiet] -quiet

# IP: bd/proc_system/ip/proc_system_axi_iic_0_1/proc_system_axi_iic_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==proc_system_axi_iic_0_1 || ORIG_REF_NAME==proc_system_axi_iic_0_1} -quiet] -quiet

# IP: bd/proc_system/ip/proc_system_xbar_0/proc_system_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==proc_system_xbar_0 || ORIG_REF_NAME==proc_system_xbar_0} -quiet] -quiet

# IP: bd/proc_system/ip/proc_system_ps7_0_axi_periph_0/proc_system_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==proc_system_ps7_0_axi_periph_0 || ORIG_REF_NAME==proc_system_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/proc_system/ip/proc_system_rst_ps7_0_50M_0/proc_system_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==proc_system_rst_ps7_0_50M_0 || ORIG_REF_NAME==proc_system_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/proc_system/ip/proc_system_axi_fifo_mm_s_0_0/proc_system_axi_fifo_mm_s_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==proc_system_axi_fifo_mm_s_0_0 || ORIG_REF_NAME==proc_system_axi_fifo_mm_s_0_0} -quiet] -quiet

# IP: bd/proc_system/ip/proc_system_axis_data_fifo_0_0/proc_system_axis_data_fifo_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==proc_system_axis_data_fifo_0_0 || ORIG_REF_NAME==proc_system_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/proc_system/ip/proc_system_system_ila_0_0/proc_system_system_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==proc_system_system_ila_0_0 || ORIG_REF_NAME==proc_system_system_ila_0_0} -quiet] -quiet

# IP: bd/proc_system/ip/proc_system_auto_pc_0/proc_system_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==proc_system_auto_pc_0 || ORIG_REF_NAME==proc_system_auto_pc_0} -quiet] -quiet

# XDC: d:/Dirk/Grad_School/525.742.8VL_SOC/HW/Module2/lab2/vivado/lab2.gen/sources_1/bd/proc_system/proc_system_ooc.xdc
