# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Dirk/Grad_School/525.742.8VL_SOC/HW/Module2/lab2/vivado/lab2.srcs/sources_1/bd/proc_system/ip/proc_system_processing_system7_0_0/proc_system_processing_system7_0_0.xci
# IP: The module: 'proc_system_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Dirk/Grad_School/525.742.8VL_SOC/HW/Module2/lab2/vivado/lab2.gen/sources_1/bd/proc_system/ip/proc_system_processing_system7_0_0/proc_system_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'proc_system_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/Dirk/Grad_School/525.742.8VL_SOC/HW/Module2/lab2/vivado/lab2.srcs/sources_1/bd/proc_system/ip/proc_system_processing_system7_0_0/proc_system_processing_system7_0_0.xci
# IP: The module: 'proc_system_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Dirk/Grad_School/525.742.8VL_SOC/HW/Module2/lab2/vivado/lab2.gen/sources_1/bd/proc_system/ip/proc_system_processing_system7_0_0/proc_system_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'proc_system_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
