# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Dirk/Grad_School/525.742.8VL_SOC/HW/Module6/lab6/radio_periph_lab_main/vivado/radio_periph_lab.srcs/sources_1/bd/design_1/ip/design_1_full_radio_0_0/design_1_full_radio_0_0.xci
# IP: The module: 'design_1_full_radio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/Dirk/Grad_School/525.742.8VL_SOC/HW/Module6/lab6/radio_periph_lab_main/vivado/radio_periph_lab.gen/sources_1/bd/design_1/ip/design_1_full_radio_0_0/src/dds_compiler_0/dds_compiler_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dds_compiler_0 || ORIG_REF_NAME==dds_compiler_0} -quiet] -quiet

# IP: D:/Dirk/Grad_School/525.742.8VL_SOC/HW/Module6/lab6/radio_periph_lab_main/vivado/radio_periph_lab.srcs/sources_1/bd/design_1/ip/design_1_full_radio_0_0/design_1_full_radio_0_0.xci
# IP: The module: 'design_1_full_radio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/Dirk/Grad_School/525.742.8VL_SOC/HW/Module6/lab6/radio_periph_lab_main/vivado/radio_periph_lab.gen/sources_1/bd/design_1/ip/design_1_full_radio_0_0/src/dds_compiler_0/dds_compiler_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dds_compiler_0 || ORIG_REF_NAME==dds_compiler_0} -quiet] -quiet
